Repository Nemu627/Hello-World, pull requests merged in 2022-03, with the labels that each got.

#6 C#を追加した。
  C#/HelloWorld.cs
Labels: invalid

#7 Scheme
  Scheme/Hello-World.scm
Labels: documentation

#8 add: CoffeeScript
  CoffeeScript/hello-world.coffee
Labels: documentation

#10 asd: Lua
  Lua/hello-world.lua
Labels: documentation

#11 add: nim
  Nim/Hello-World.nim
Labels: documentation

#12 add: scala
  Scala/Hello-World.scala
Labels: documentation

#14 Added some languages
  AppleScript/Hello-World.applescript
  COBOL/Hello-World.cbl
  Emojicode/Hello-World.emojic
  Hodor/Hello-World.hd
  PowerShell/Hello-World.ps1
  Ring/Hello-World.ring
  TTSNeo/Hello-World.ttsneo
Labels: documentation, help wanted
